on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Эта задача оставляет комментарий к пулл реквесту
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            Привет! :wink: Это твой первый Pull Request! Поздравляю тебя :)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
